// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/proxysource"
)

// ProxySourceCreate is the builder for creating a ProxySource entity.
type ProxySourceCreate struct {
	config
	mutation *ProxySourceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxySourceCreate) SetCreatedAt(v time.Time) *ProxySourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxySourceCreate) SetNillableCreatedAt(v *time.Time) *ProxySourceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxySourceCreate) SetUpdatedAt(v time.Time) *ProxySourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxySourceCreate) SetNillableUpdatedAt(v *time.Time) *ProxySourceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ProxySourceCreate) SetDeletedAt(v time.Time) *ProxySourceCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ProxySourceCreate) SetNillableDeletedAt(v *time.Time) *ProxySourceCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *ProxySourceCreate) SetOwnerUserID(v int64) *ProxySourceCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_c *ProxySourceCreate) SetNillableOwnerUserID(v *int64) *ProxySourceCreate {
	if v != nil {
		_c.SetOwnerUserID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ProxySourceCreate) SetName(v string) *ProxySourceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSubscriptionURL sets the "subscription_url" field.
func (_c *ProxySourceCreate) SetSubscriptionURL(v string) *ProxySourceCreate {
	_c.mutation.SetSubscriptionURL(v)
	return _c
}

// SetIsPublic sets the "is_public" field.
func (_c *ProxySourceCreate) SetIsPublic(v bool) *ProxySourceCreate {
	_c.mutation.SetIsPublic(v)
	return _c
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_c *ProxySourceCreate) SetNillableIsPublic(v *bool) *ProxySourceCreate {
	if v != nil {
		_c.SetIsPublic(*v)
	}
	return _c
}

// SetRefreshIntervalMinutes sets the "refresh_interval_minutes" field.
func (_c *ProxySourceCreate) SetRefreshIntervalMinutes(v int) *ProxySourceCreate {
	_c.mutation.SetRefreshIntervalMinutes(v)
	return _c
}

// SetNillableRefreshIntervalMinutes sets the "refresh_interval_minutes" field if the given value is not nil.
func (_c *ProxySourceCreate) SetNillableRefreshIntervalMinutes(v *int) *ProxySourceCreate {
	if v != nil {
		_c.SetRefreshIntervalMinutes(*v)
	}
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *ProxySourceCreate) SetLastSyncedAt(v time.Time) *ProxySourceCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_c *ProxySourceCreate) SetNillableLastSyncedAt(v *time.Time) *ProxySourceCreate {
	if v != nil {
		_c.SetLastSyncedAt(*v)
	}
	return _c
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (_c *ProxySourceCreate) SetLastSyncStatus(v string) *ProxySourceCreate {
	_c.mutation.SetLastSyncStatus(v)
	return _c
}

// SetNillableLastSyncStatus sets the "last_sync_status" field if the given value is not nil.
func (_c *ProxySourceCreate) SetNillableLastSyncStatus(v *string) *ProxySourceCreate {
	if v != nil {
		_c.SetLastSyncStatus(*v)
	}
	return _c
}

// SetLastSyncError sets the "last_sync_error" field.
func (_c *ProxySourceCreate) SetLastSyncError(v string) *ProxySourceCreate {
	_c.mutation.SetLastSyncError(v)
	return _c
}

// SetNillableLastSyncError sets the "last_sync_error" field if the given value is not nil.
func (_c *ProxySourceCreate) SetNillableLastSyncError(v *string) *ProxySourceCreate {
	if v != nil {
		_c.SetLastSyncError(*v)
	}
	return _c
}

// SetLastImportedCount sets the "last_imported_count" field.
func (_c *ProxySourceCreate) SetLastImportedCount(v int) *ProxySourceCreate {
	_c.mutation.SetLastImportedCount(v)
	return _c
}

// SetNillableLastImportedCount sets the "last_imported_count" field if the given value is not nil.
func (_c *ProxySourceCreate) SetNillableLastImportedCount(v *int) *ProxySourceCreate {
	if v != nil {
		_c.SetLastImportedCount(*v)
	}
	return _c
}

// SetSyncEnabled sets the "sync_enabled" field.
func (_c *ProxySourceCreate) SetSyncEnabled(v bool) *ProxySourceCreate {
	_c.mutation.SetSyncEnabled(v)
	return _c
}

// SetNillableSyncEnabled sets the "sync_enabled" field if the given value is not nil.
func (_c *ProxySourceCreate) SetNillableSyncEnabled(v *bool) *ProxySourceCreate {
	if v != nil {
		_c.SetSyncEnabled(*v)
	}
	return _c
}

// SetSubTrafficUsed sets the "sub_traffic_used" field.
func (_c *ProxySourceCreate) SetSubTrafficUsed(v int64) *ProxySourceCreate {
	_c.mutation.SetSubTrafficUsed(v)
	return _c
}

// SetNillableSubTrafficUsed sets the "sub_traffic_used" field if the given value is not nil.
func (_c *ProxySourceCreate) SetNillableSubTrafficUsed(v *int64) *ProxySourceCreate {
	if v != nil {
		_c.SetSubTrafficUsed(*v)
	}
	return _c
}

// SetSubTrafficTotal sets the "sub_traffic_total" field.
func (_c *ProxySourceCreate) SetSubTrafficTotal(v int64) *ProxySourceCreate {
	_c.mutation.SetSubTrafficTotal(v)
	return _c
}

// SetNillableSubTrafficTotal sets the "sub_traffic_total" field if the given value is not nil.
func (_c *ProxySourceCreate) SetNillableSubTrafficTotal(v *int64) *ProxySourceCreate {
	if v != nil {
		_c.SetSubTrafficTotal(*v)
	}
	return _c
}

// SetSubExpiresAt sets the "sub_expires_at" field.
func (_c *ProxySourceCreate) SetSubExpiresAt(v time.Time) *ProxySourceCreate {
	_c.mutation.SetSubExpiresAt(v)
	return _c
}

// SetNillableSubExpiresAt sets the "sub_expires_at" field if the given value is not nil.
func (_c *ProxySourceCreate) SetNillableSubExpiresAt(v *time.Time) *ProxySourceCreate {
	if v != nil {
		_c.SetSubExpiresAt(*v)
	}
	return _c
}

// SetSubInfoUpdatedAt sets the "sub_info_updated_at" field.
func (_c *ProxySourceCreate) SetSubInfoUpdatedAt(v time.Time) *ProxySourceCreate {
	_c.mutation.SetSubInfoUpdatedAt(v)
	return _c
}

// SetNillableSubInfoUpdatedAt sets the "sub_info_updated_at" field if the given value is not nil.
func (_c *ProxySourceCreate) SetNillableSubInfoUpdatedAt(v *time.Time) *ProxySourceCreate {
	if v != nil {
		_c.SetSubInfoUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ProxySourceMutation object of the builder.
func (_c *ProxySourceCreate) Mutation() *ProxySourceMutation {
	return _c.mutation
}

// Save creates the ProxySource in the database.
func (_c *ProxySourceCreate) Save(ctx context.Context) (*ProxySource, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxySourceCreate) SaveX(ctx context.Context) *ProxySource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxySourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxySourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxySourceCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if proxysource.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxysource.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := proxysource.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if proxysource.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxysource.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxysource.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		v := proxysource.DefaultIsPublic
		_c.mutation.SetIsPublic(v)
	}
	if _, ok := _c.mutation.RefreshIntervalMinutes(); !ok {
		v := proxysource.DefaultRefreshIntervalMinutes
		_c.mutation.SetRefreshIntervalMinutes(v)
	}
	if _, ok := _c.mutation.LastSyncStatus(); !ok {
		v := proxysource.DefaultLastSyncStatus
		_c.mutation.SetLastSyncStatus(v)
	}
	if _, ok := _c.mutation.LastImportedCount(); !ok {
		v := proxysource.DefaultLastImportedCount
		_c.mutation.SetLastImportedCount(v)
	}
	if _, ok := _c.mutation.SyncEnabled(); !ok {
		v := proxysource.DefaultSyncEnabled
		_c.mutation.SetSyncEnabled(v)
	}
	if _, ok := _c.mutation.SubTrafficUsed(); !ok {
		v := proxysource.DefaultSubTrafficUsed
		_c.mutation.SetSubTrafficUsed(v)
	}
	if _, ok := _c.mutation.SubTrafficTotal(); !ok {
		v := proxysource.DefaultSubTrafficTotal
		_c.mutation.SetSubTrafficTotal(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxySourceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxySource.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxySource.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProxySource.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := proxysource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxySource.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubscriptionURL(); !ok {
		return &ValidationError{Name: "subscription_url", err: errors.New(`ent: missing required field "ProxySource.subscription_url"`)}
	}
	if v, ok := _c.mutation.SubscriptionURL(); ok {
		if err := proxysource.SubscriptionURLValidator(v); err != nil {
			return &ValidationError{Name: "subscription_url", err: fmt.Errorf(`ent: validator failed for field "ProxySource.subscription_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		return &ValidationError{Name: "is_public", err: errors.New(`ent: missing required field "ProxySource.is_public"`)}
	}
	if _, ok := _c.mutation.RefreshIntervalMinutes(); !ok {
		return &ValidationError{Name: "refresh_interval_minutes", err: errors.New(`ent: missing required field "ProxySource.refresh_interval_minutes"`)}
	}
	if _, ok := _c.mutation.LastSyncStatus(); !ok {
		return &ValidationError{Name: "last_sync_status", err: errors.New(`ent: missing required field "ProxySource.last_sync_status"`)}
	}
	if v, ok := _c.mutation.LastSyncStatus(); ok {
		if err := proxysource.LastSyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_sync_status", err: fmt.Errorf(`ent: validator failed for field "ProxySource.last_sync_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastImportedCount(); !ok {
		return &ValidationError{Name: "last_imported_count", err: errors.New(`ent: missing required field "ProxySource.last_imported_count"`)}
	}
	if _, ok := _c.mutation.SyncEnabled(); !ok {
		return &ValidationError{Name: "sync_enabled", err: errors.New(`ent: missing required field "ProxySource.sync_enabled"`)}
	}
	if _, ok := _c.mutation.SubTrafficUsed(); !ok {
		return &ValidationError{Name: "sub_traffic_used", err: errors.New(`ent: missing required field "ProxySource.sub_traffic_used"`)}
	}
	if _, ok := _c.mutation.SubTrafficTotal(); !ok {
		return &ValidationError{Name: "sub_traffic_total", err: errors.New(`ent: missing required field "ProxySource.sub_traffic_total"`)}
	}
	return nil
}

func (_c *ProxySourceCreate) sqlSave(ctx context.Context) (*ProxySource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxySourceCreate) createSpec() (*ProxySource, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxySource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxysource.Table, sqlgraph.NewFieldSpec(proxysource.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxysource.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysource.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(proxysource.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(proxysource.FieldOwnerUserID, field.TypeInt64, value)
		_node.OwnerUserID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(proxysource.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SubscriptionURL(); ok {
		_spec.SetField(proxysource.FieldSubscriptionURL, field.TypeString, value)
		_node.SubscriptionURL = value
	}
	if value, ok := _c.mutation.IsPublic(); ok {
		_spec.SetField(proxysource.FieldIsPublic, field.TypeBool, value)
		_node.IsPublic = value
	}
	if value, ok := _c.mutation.RefreshIntervalMinutes(); ok {
		_spec.SetField(proxysource.FieldRefreshIntervalMinutes, field.TypeInt, value)
		_node.RefreshIntervalMinutes = value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(proxysource.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = &value
	}
	if value, ok := _c.mutation.LastSyncStatus(); ok {
		_spec.SetField(proxysource.FieldLastSyncStatus, field.TypeString, value)
		_node.LastSyncStatus = value
	}
	if value, ok := _c.mutation.LastSyncError(); ok {
		_spec.SetField(proxysource.FieldLastSyncError, field.TypeString, value)
		_node.LastSyncError = &value
	}
	if value, ok := _c.mutation.LastImportedCount(); ok {
		_spec.SetField(proxysource.FieldLastImportedCount, field.TypeInt, value)
		_node.LastImportedCount = value
	}
	if value, ok := _c.mutation.SyncEnabled(); ok {
		_spec.SetField(proxysource.FieldSyncEnabled, field.TypeBool, value)
		_node.SyncEnabled = value
	}
	if value, ok := _c.mutation.SubTrafficUsed(); ok {
		_spec.SetField(proxysource.FieldSubTrafficUsed, field.TypeInt64, value)
		_node.SubTrafficUsed = value
	}
	if value, ok := _c.mutation.SubTrafficTotal(); ok {
		_spec.SetField(proxysource.FieldSubTrafficTotal, field.TypeInt64, value)
		_node.SubTrafficTotal = value
	}
	if value, ok := _c.mutation.SubExpiresAt(); ok {
		_spec.SetField(proxysource.FieldSubExpiresAt, field.TypeTime, value)
		_node.SubExpiresAt = &value
	}
	if value, ok := _c.mutation.SubInfoUpdatedAt(); ok {
		_spec.SetField(proxysource.FieldSubInfoUpdatedAt, field.TypeTime, value)
		_node.SubInfoUpdatedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxySource.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxySourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxySourceCreate) OnConflict(opts ...sql.ConflictOption) *ProxySourceUpsertOne {
	_c.conflict = opts
	return &ProxySourceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxySource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxySourceCreate) OnConflictColumns(columns ...string) *ProxySourceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxySourceUpsertOne{
		create: _c,
	}
}

type (
	// ProxySourceUpsertOne is the builder for "upsert"-ing
	//  one ProxySource node.
	ProxySourceUpsertOne struct {
		create *ProxySourceCreate
	}

	// ProxySourceUpsert is the "OnConflict" setter.
	ProxySourceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxySourceUpsert) SetUpdatedAt(v time.Time) *ProxySourceUpsert {
	u.Set(proxysource.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateUpdatedAt() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProxySourceUpsert) SetDeletedAt(v time.Time) *ProxySourceUpsert {
	u.Set(proxysource.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateDeletedAt() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProxySourceUpsert) ClearDeletedAt() *ProxySourceUpsert {
	u.SetNull(proxysource.FieldDeletedAt)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *ProxySourceUpsert) SetOwnerUserID(v int64) *ProxySourceUpsert {
	u.Set(proxysource.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateOwnerUserID() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldOwnerUserID)
	return u
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *ProxySourceUpsert) AddOwnerUserID(v int64) *ProxySourceUpsert {
	u.Add(proxysource.FieldOwnerUserID, v)
	return u
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (u *ProxySourceUpsert) ClearOwnerUserID() *ProxySourceUpsert {
	u.SetNull(proxysource.FieldOwnerUserID)
	return u
}

// SetName sets the "name" field.
func (u *ProxySourceUpsert) SetName(v string) *ProxySourceUpsert {
	u.Set(proxysource.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateName() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldName)
	return u
}

// SetSubscriptionURL sets the "subscription_url" field.
func (u *ProxySourceUpsert) SetSubscriptionURL(v string) *ProxySourceUpsert {
	u.Set(proxysource.FieldSubscriptionURL, v)
	return u
}

// UpdateSubscriptionURL sets the "subscription_url" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateSubscriptionURL() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldSubscriptionURL)
	return u
}

// SetIsPublic sets the "is_public" field.
func (u *ProxySourceUpsert) SetIsPublic(v bool) *ProxySourceUpsert {
	u.Set(proxysource.FieldIsPublic, v)
	return u
}

// UpdateIsPublic sets the "is_public" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateIsPublic() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldIsPublic)
	return u
}

// SetRefreshIntervalMinutes sets the "refresh_interval_minutes" field.
func (u *ProxySourceUpsert) SetRefreshIntervalMinutes(v int) *ProxySourceUpsert {
	u.Set(proxysource.FieldRefreshIntervalMinutes, v)
	return u
}

// UpdateRefreshIntervalMinutes sets the "refresh_interval_minutes" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateRefreshIntervalMinutes() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldRefreshIntervalMinutes)
	return u
}

// AddRefreshIntervalMinutes adds v to the "refresh_interval_minutes" field.
func (u *ProxySourceUpsert) AddRefreshIntervalMinutes(v int) *ProxySourceUpsert {
	u.Add(proxysource.FieldRefreshIntervalMinutes, v)
	return u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *ProxySourceUpsert) SetLastSyncedAt(v time.Time) *ProxySourceUpsert {
	u.Set(proxysource.FieldLastSyncedAt, v)
	return u
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateLastSyncedAt() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldLastSyncedAt)
	return u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *ProxySourceUpsert) ClearLastSyncedAt() *ProxySourceUpsert {
	u.SetNull(proxysource.FieldLastSyncedAt)
	return u
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (u *ProxySourceUpsert) SetLastSyncStatus(v string) *ProxySourceUpsert {
	u.Set(proxysource.FieldLastSyncStatus, v)
	return u
}

// UpdateLastSyncStatus sets the "last_sync_status" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateLastSyncStatus() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldLastSyncStatus)
	return u
}

// SetLastSyncError sets the "last_sync_error" field.
func (u *ProxySourceUpsert) SetLastSyncError(v string) *ProxySourceUpsert {
	u.Set(proxysource.FieldLastSyncError, v)
	return u
}

// UpdateLastSyncError sets the "last_sync_error" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateLastSyncError() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldLastSyncError)
	return u
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (u *ProxySourceUpsert) ClearLastSyncError() *ProxySourceUpsert {
	u.SetNull(proxysource.FieldLastSyncError)
	return u
}

// SetLastImportedCount sets the "last_imported_count" field.
func (u *ProxySourceUpsert) SetLastImportedCount(v int) *ProxySourceUpsert {
	u.Set(proxysource.FieldLastImportedCount, v)
	return u
}

// UpdateLastImportedCount sets the "last_imported_count" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateLastImportedCount() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldLastImportedCount)
	return u
}

// AddLastImportedCount adds v to the "last_imported_count" field.
func (u *ProxySourceUpsert) AddLastImportedCount(v int) *ProxySourceUpsert {
	u.Add(proxysource.FieldLastImportedCount, v)
	return u
}

// SetSyncEnabled sets the "sync_enabled" field.
func (u *ProxySourceUpsert) SetSyncEnabled(v bool) *ProxySourceUpsert {
	u.Set(proxysource.FieldSyncEnabled, v)
	return u
}

// UpdateSyncEnabled sets the "sync_enabled" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateSyncEnabled() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldSyncEnabled)
	return u
}

// SetSubTrafficUsed sets the "sub_traffic_used" field.
func (u *ProxySourceUpsert) SetSubTrafficUsed(v int64) *ProxySourceUpsert {
	u.Set(proxysource.FieldSubTrafficUsed, v)
	return u
}

// UpdateSubTrafficUsed sets the "sub_traffic_used" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateSubTrafficUsed() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldSubTrafficUsed)
	return u
}

// AddSubTrafficUsed adds v to the "sub_traffic_used" field.
func (u *ProxySourceUpsert) AddSubTrafficUsed(v int64) *ProxySourceUpsert {
	u.Add(proxysource.FieldSubTrafficUsed, v)
	return u
}

// SetSubTrafficTotal sets the "sub_traffic_total" field.
func (u *ProxySourceUpsert) SetSubTrafficTotal(v int64) *ProxySourceUpsert {
	u.Set(proxysource.FieldSubTrafficTotal, v)
	return u
}

// UpdateSubTrafficTotal sets the "sub_traffic_total" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateSubTrafficTotal() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldSubTrafficTotal)
	return u
}

// AddSubTrafficTotal adds v to the "sub_traffic_total" field.
func (u *ProxySourceUpsert) AddSubTrafficTotal(v int64) *ProxySourceUpsert {
	u.Add(proxysource.FieldSubTrafficTotal, v)
	return u
}

// SetSubExpiresAt sets the "sub_expires_at" field.
func (u *ProxySourceUpsert) SetSubExpiresAt(v time.Time) *ProxySourceUpsert {
	u.Set(proxysource.FieldSubExpiresAt, v)
	return u
}

// UpdateSubExpiresAt sets the "sub_expires_at" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateSubExpiresAt() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldSubExpiresAt)
	return u
}

// ClearSubExpiresAt clears the value of the "sub_expires_at" field.
func (u *ProxySourceUpsert) ClearSubExpiresAt() *ProxySourceUpsert {
	u.SetNull(proxysource.FieldSubExpiresAt)
	return u
}

// SetSubInfoUpdatedAt sets the "sub_info_updated_at" field.
func (u *ProxySourceUpsert) SetSubInfoUpdatedAt(v time.Time) *ProxySourceUpsert {
	u.Set(proxysource.FieldSubInfoUpdatedAt, v)
	return u
}

// UpdateSubInfoUpdatedAt sets the "sub_info_updated_at" field to the value that was provided on create.
func (u *ProxySourceUpsert) UpdateSubInfoUpdatedAt() *ProxySourceUpsert {
	u.SetExcluded(proxysource.FieldSubInfoUpdatedAt)
	return u
}

// ClearSubInfoUpdatedAt clears the value of the "sub_info_updated_at" field.
func (u *ProxySourceUpsert) ClearSubInfoUpdatedAt() *ProxySourceUpsert {
	u.SetNull(proxysource.FieldSubInfoUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProxySource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxySourceUpsertOne) UpdateNewValues() *ProxySourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(proxysource.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxySource.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProxySourceUpsertOne) Ignore() *ProxySourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxySourceUpsertOne) DoNothing() *ProxySourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxySourceCreate.OnConflict
// documentation for more info.
func (u *ProxySourceUpsertOne) Update(set func(*ProxySourceUpsert)) *ProxySourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxySourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxySourceUpsertOne) SetUpdatedAt(v time.Time) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateUpdatedAt() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProxySourceUpsertOne) SetDeletedAt(v time.Time) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateDeletedAt() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProxySourceUpsertOne) ClearDeletedAt() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *ProxySourceUpsertOne) SetOwnerUserID(v int64) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *ProxySourceUpsertOne) AddOwnerUserID(v int64) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateOwnerUserID() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateOwnerUserID()
	})
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (u *ProxySourceUpsertOne) ClearOwnerUserID() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.ClearOwnerUserID()
	})
}

// SetName sets the "name" field.
func (u *ProxySourceUpsertOne) SetName(v string) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateName() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateName()
	})
}

// SetSubscriptionURL sets the "subscription_url" field.
func (u *ProxySourceUpsertOne) SetSubscriptionURL(v string) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetSubscriptionURL(v)
	})
}

// UpdateSubscriptionURL sets the "subscription_url" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateSubscriptionURL() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateSubscriptionURL()
	})
}

// SetIsPublic sets the "is_public" field.
func (u *ProxySourceUpsertOne) SetIsPublic(v bool) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetIsPublic(v)
	})
}

// UpdateIsPublic sets the "is_public" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateIsPublic() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateIsPublic()
	})
}

// SetRefreshIntervalMinutes sets the "refresh_interval_minutes" field.
func (u *ProxySourceUpsertOne) SetRefreshIntervalMinutes(v int) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetRefreshIntervalMinutes(v)
	})
}

// AddRefreshIntervalMinutes adds v to the "refresh_interval_minutes" field.
func (u *ProxySourceUpsertOne) AddRefreshIntervalMinutes(v int) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.AddRefreshIntervalMinutes(v)
	})
}

// UpdateRefreshIntervalMinutes sets the "refresh_interval_minutes" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateRefreshIntervalMinutes() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateRefreshIntervalMinutes()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *ProxySourceUpsertOne) SetLastSyncedAt(v time.Time) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateLastSyncedAt() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *ProxySourceUpsertOne) ClearLastSyncedAt() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.ClearLastSyncedAt()
	})
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (u *ProxySourceUpsertOne) SetLastSyncStatus(v string) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetLastSyncStatus(v)
	})
}

// UpdateLastSyncStatus sets the "last_sync_status" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateLastSyncStatus() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateLastSyncStatus()
	})
}

// SetLastSyncError sets the "last_sync_error" field.
func (u *ProxySourceUpsertOne) SetLastSyncError(v string) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetLastSyncError(v)
	})
}

// UpdateLastSyncError sets the "last_sync_error" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateLastSyncError() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateLastSyncError()
	})
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (u *ProxySourceUpsertOne) ClearLastSyncError() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.ClearLastSyncError()
	})
}

// SetLastImportedCount sets the "last_imported_count" field.
func (u *ProxySourceUpsertOne) SetLastImportedCount(v int) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetLastImportedCount(v)
	})
}

// AddLastImportedCount adds v to the "last_imported_count" field.
func (u *ProxySourceUpsertOne) AddLastImportedCount(v int) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.AddLastImportedCount(v)
	})
}

// UpdateLastImportedCount sets the "last_imported_count" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateLastImportedCount() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateLastImportedCount()
	})
}

// SetSyncEnabled sets the "sync_enabled" field.
func (u *ProxySourceUpsertOne) SetSyncEnabled(v bool) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetSyncEnabled(v)
	})
}

// UpdateSyncEnabled sets the "sync_enabled" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateSyncEnabled() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateSyncEnabled()
	})
}

// SetSubTrafficUsed sets the "sub_traffic_used" field.
func (u *ProxySourceUpsertOne) SetSubTrafficUsed(v int64) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetSubTrafficUsed(v)
	})
}

// AddSubTrafficUsed adds v to the "sub_traffic_used" field.
func (u *ProxySourceUpsertOne) AddSubTrafficUsed(v int64) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.AddSubTrafficUsed(v)
	})
}

// UpdateSubTrafficUsed sets the "sub_traffic_used" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateSubTrafficUsed() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateSubTrafficUsed()
	})
}

// SetSubTrafficTotal sets the "sub_traffic_total" field.
func (u *ProxySourceUpsertOne) SetSubTrafficTotal(v int64) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetSubTrafficTotal(v)
	})
}

// AddSubTrafficTotal adds v to the "sub_traffic_total" field.
func (u *ProxySourceUpsertOne) AddSubTrafficTotal(v int64) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.AddSubTrafficTotal(v)
	})
}

// UpdateSubTrafficTotal sets the "sub_traffic_total" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateSubTrafficTotal() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateSubTrafficTotal()
	})
}

// SetSubExpiresAt sets the "sub_expires_at" field.
func (u *ProxySourceUpsertOne) SetSubExpiresAt(v time.Time) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetSubExpiresAt(v)
	})
}

// UpdateSubExpiresAt sets the "sub_expires_at" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateSubExpiresAt() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateSubExpiresAt()
	})
}

// ClearSubExpiresAt clears the value of the "sub_expires_at" field.
func (u *ProxySourceUpsertOne) ClearSubExpiresAt() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.ClearSubExpiresAt()
	})
}

// SetSubInfoUpdatedAt sets the "sub_info_updated_at" field.
func (u *ProxySourceUpsertOne) SetSubInfoUpdatedAt(v time.Time) *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetSubInfoUpdatedAt(v)
	})
}

// UpdateSubInfoUpdatedAt sets the "sub_info_updated_at" field to the value that was provided on create.
func (u *ProxySourceUpsertOne) UpdateSubInfoUpdatedAt() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateSubInfoUpdatedAt()
	})
}

// ClearSubInfoUpdatedAt clears the value of the "sub_info_updated_at" field.
func (u *ProxySourceUpsertOne) ClearSubInfoUpdatedAt() *ProxySourceUpsertOne {
	return u.Update(func(s *ProxySourceUpsert) {
		s.ClearSubInfoUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProxySourceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxySourceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxySourceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProxySourceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProxySourceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProxySourceCreateBulk is the builder for creating many ProxySource entities in bulk.
type ProxySourceCreateBulk struct {
	config
	err      error
	builders []*ProxySourceCreate
	conflict []sql.ConflictOption
}

// Save creates the ProxySource entities in the database.
func (_c *ProxySourceCreateBulk) Save(ctx context.Context) ([]*ProxySource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxySource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxySourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxySourceCreateBulk) SaveX(ctx context.Context) []*ProxySource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxySourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxySourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxySource.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxySourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxySourceCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProxySourceUpsertBulk {
	_c.conflict = opts
	return &ProxySourceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxySource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxySourceCreateBulk) OnConflictColumns(columns ...string) *ProxySourceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxySourceUpsertBulk{
		create: _c,
	}
}

// ProxySourceUpsertBulk is the builder for "upsert"-ing
// a bulk of ProxySource nodes.
type ProxySourceUpsertBulk struct {
	create *ProxySourceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProxySource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxySourceUpsertBulk) UpdateNewValues() *ProxySourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(proxysource.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxySource.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProxySourceUpsertBulk) Ignore() *ProxySourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxySourceUpsertBulk) DoNothing() *ProxySourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxySourceCreateBulk.OnConflict
// documentation for more info.
func (u *ProxySourceUpsertBulk) Update(set func(*ProxySourceUpsert)) *ProxySourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxySourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxySourceUpsertBulk) SetUpdatedAt(v time.Time) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateUpdatedAt() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ProxySourceUpsertBulk) SetDeletedAt(v time.Time) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateDeletedAt() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ProxySourceUpsertBulk) ClearDeletedAt() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *ProxySourceUpsertBulk) SetOwnerUserID(v int64) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetOwnerUserID(v)
	})
}

// AddOwnerUserID adds v to the "owner_user_id" field.
func (u *ProxySourceUpsertBulk) AddOwnerUserID(v int64) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.AddOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateOwnerUserID() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateOwnerUserID()
	})
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (u *ProxySourceUpsertBulk) ClearOwnerUserID() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.ClearOwnerUserID()
	})
}

// SetName sets the "name" field.
func (u *ProxySourceUpsertBulk) SetName(v string) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateName() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateName()
	})
}

// SetSubscriptionURL sets the "subscription_url" field.
func (u *ProxySourceUpsertBulk) SetSubscriptionURL(v string) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetSubscriptionURL(v)
	})
}

// UpdateSubscriptionURL sets the "subscription_url" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateSubscriptionURL() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateSubscriptionURL()
	})
}

// SetIsPublic sets the "is_public" field.
func (u *ProxySourceUpsertBulk) SetIsPublic(v bool) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetIsPublic(v)
	})
}

// UpdateIsPublic sets the "is_public" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateIsPublic() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateIsPublic()
	})
}

// SetRefreshIntervalMinutes sets the "refresh_interval_minutes" field.
func (u *ProxySourceUpsertBulk) SetRefreshIntervalMinutes(v int) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetRefreshIntervalMinutes(v)
	})
}

// AddRefreshIntervalMinutes adds v to the "refresh_interval_minutes" field.
func (u *ProxySourceUpsertBulk) AddRefreshIntervalMinutes(v int) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.AddRefreshIntervalMinutes(v)
	})
}

// UpdateRefreshIntervalMinutes sets the "refresh_interval_minutes" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateRefreshIntervalMinutes() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateRefreshIntervalMinutes()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *ProxySourceUpsertBulk) SetLastSyncedAt(v time.Time) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateLastSyncedAt() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *ProxySourceUpsertBulk) ClearLastSyncedAt() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.ClearLastSyncedAt()
	})
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (u *ProxySourceUpsertBulk) SetLastSyncStatus(v string) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetLastSyncStatus(v)
	})
}

// UpdateLastSyncStatus sets the "last_sync_status" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateLastSyncStatus() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateLastSyncStatus()
	})
}

// SetLastSyncError sets the "last_sync_error" field.
func (u *ProxySourceUpsertBulk) SetLastSyncError(v string) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetLastSyncError(v)
	})
}

// UpdateLastSyncError sets the "last_sync_error" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateLastSyncError() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateLastSyncError()
	})
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (u *ProxySourceUpsertBulk) ClearLastSyncError() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.ClearLastSyncError()
	})
}

// SetLastImportedCount sets the "last_imported_count" field.
func (u *ProxySourceUpsertBulk) SetLastImportedCount(v int) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetLastImportedCount(v)
	})
}

// AddLastImportedCount adds v to the "last_imported_count" field.
func (u *ProxySourceUpsertBulk) AddLastImportedCount(v int) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.AddLastImportedCount(v)
	})
}

// UpdateLastImportedCount sets the "last_imported_count" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateLastImportedCount() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateLastImportedCount()
	})
}

// SetSyncEnabled sets the "sync_enabled" field.
func (u *ProxySourceUpsertBulk) SetSyncEnabled(v bool) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetSyncEnabled(v)
	})
}

// UpdateSyncEnabled sets the "sync_enabled" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateSyncEnabled() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateSyncEnabled()
	})
}

// SetSubTrafficUsed sets the "sub_traffic_used" field.
func (u *ProxySourceUpsertBulk) SetSubTrafficUsed(v int64) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetSubTrafficUsed(v)
	})
}

// AddSubTrafficUsed adds v to the "sub_traffic_used" field.
func (u *ProxySourceUpsertBulk) AddSubTrafficUsed(v int64) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.AddSubTrafficUsed(v)
	})
}

// UpdateSubTrafficUsed sets the "sub_traffic_used" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateSubTrafficUsed() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateSubTrafficUsed()
	})
}

// SetSubTrafficTotal sets the "sub_traffic_total" field.
func (u *ProxySourceUpsertBulk) SetSubTrafficTotal(v int64) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetSubTrafficTotal(v)
	})
}

// AddSubTrafficTotal adds v to the "sub_traffic_total" field.
func (u *ProxySourceUpsertBulk) AddSubTrafficTotal(v int64) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.AddSubTrafficTotal(v)
	})
}

// UpdateSubTrafficTotal sets the "sub_traffic_total" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateSubTrafficTotal() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateSubTrafficTotal()
	})
}

// SetSubExpiresAt sets the "sub_expires_at" field.
func (u *ProxySourceUpsertBulk) SetSubExpiresAt(v time.Time) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetSubExpiresAt(v)
	})
}

// UpdateSubExpiresAt sets the "sub_expires_at" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateSubExpiresAt() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateSubExpiresAt()
	})
}

// ClearSubExpiresAt clears the value of the "sub_expires_at" field.
func (u *ProxySourceUpsertBulk) ClearSubExpiresAt() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.ClearSubExpiresAt()
	})
}

// SetSubInfoUpdatedAt sets the "sub_info_updated_at" field.
func (u *ProxySourceUpsertBulk) SetSubInfoUpdatedAt(v time.Time) *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.SetSubInfoUpdatedAt(v)
	})
}

// UpdateSubInfoUpdatedAt sets the "sub_info_updated_at" field to the value that was provided on create.
func (u *ProxySourceUpsertBulk) UpdateSubInfoUpdatedAt() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.UpdateSubInfoUpdatedAt()
	})
}

// ClearSubInfoUpdatedAt clears the value of the "sub_info_updated_at" field.
func (u *ProxySourceUpsertBulk) ClearSubInfoUpdatedAt() *ProxySourceUpsertBulk {
	return u.Update(func(s *ProxySourceUpsert) {
		s.ClearSubInfoUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProxySourceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProxySourceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxySourceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxySourceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
