// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/proxysource"
)

// ProxySource is the model entity for the ProxySource schema.
type ProxySource struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID *int64 `json:"owner_user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// SubscriptionURL holds the value of the "subscription_url" field.
	SubscriptionURL string `json:"subscription_url,omitempty"`
	// Whether proxies imported from this source are selectable by all users.
	IsPublic bool `json:"is_public,omitempty"`
	// RefreshIntervalMinutes holds the value of the "refresh_interval_minutes" field.
	RefreshIntervalMinutes int `json:"refresh_interval_minutes,omitempty"`
	// LastSyncedAt holds the value of the "last_synced_at" field.
	LastSyncedAt *time.Time `json:"last_synced_at,omitempty"`
	// LastSyncStatus holds the value of the "last_sync_status" field.
	LastSyncStatus string `json:"last_sync_status,omitempty"`
	// LastSyncError holds the value of the "last_sync_error" field.
	LastSyncError *string `json:"last_sync_error,omitempty"`
	// LastImportedCount holds the value of the "last_imported_count" field.
	LastImportedCount int `json:"last_imported_count,omitempty"`
	// Whether the scheduler may refresh this source automatically.
	SyncEnabled bool `json:"sync_enabled,omitempty"`
	// Upload+download reported by the subscription-userinfo header, in bytes.
	SubTrafficUsed int64 `json:"sub_traffic_used,omitempty"`
	// Plan quota reported by the subscription-userinfo header, in bytes; 0 means unknown.
	SubTrafficTotal int64 `json:"sub_traffic_total,omitempty"`
	// Plan expiry reported by the subscription-userinfo header.
	SubExpiresAt *time.Time `json:"sub_expires_at,omitempty"`
	// When the subscription-userinfo snapshot above was last refreshed.
	SubInfoUpdatedAt *time.Time `json:"sub_info_updated_at,omitempty"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxySource) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxysource.FieldIsPublic, proxysource.FieldSyncEnabled:
			values[i] = new(sql.NullBool)
		case proxysource.FieldID, proxysource.FieldOwnerUserID, proxysource.FieldRefreshIntervalMinutes, proxysource.FieldLastImportedCount, proxysource.FieldSubTrafficUsed, proxysource.FieldSubTrafficTotal:
			values[i] = new(sql.NullInt64)
		case proxysource.FieldName, proxysource.FieldSubscriptionURL, proxysource.FieldLastSyncStatus, proxysource.FieldLastSyncError:
			values[i] = new(sql.NullString)
		case proxysource.FieldCreatedAt, proxysource.FieldUpdatedAt, proxysource.FieldDeletedAt, proxysource.FieldLastSyncedAt, proxysource.FieldSubExpiresAt, proxysource.FieldSubInfoUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxySource fields.
func (_m *ProxySource) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxysource.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case proxysource.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxysource.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case proxysource.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case proxysource.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = new(int64)
				*_m.OwnerUserID = value.Int64
			}
		case proxysource.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case proxysource.FieldSubscriptionURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_url", values[i])
			} else if value.Valid {
				_m.SubscriptionURL = value.String
			}
		case proxysource.FieldIsPublic:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_public", values[i])
			} else if value.Valid {
				_m.IsPublic = value.Bool
			}
		case proxysource.FieldRefreshIntervalMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_interval_minutes", values[i])
			} else if value.Valid {
				_m.RefreshIntervalMinutes = int(value.Int64)
			}
		case proxysource.FieldLastSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_synced_at", values[i])
			} else if value.Valid {
				_m.LastSyncedAt = new(time.Time)
				*_m.LastSyncedAt = value.Time
			}
		case proxysource.FieldLastSyncStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_status", values[i])
			} else if value.Valid {
				_m.LastSyncStatus = value.String
			}
		case proxysource.FieldLastSyncError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_error", values[i])
			} else if value.Valid {
				_m.LastSyncError = new(string)
				*_m.LastSyncError = value.String
			}
		case proxysource.FieldLastImportedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_imported_count", values[i])
			} else if value.Valid {
				_m.LastImportedCount = int(value.Int64)
			}
		case proxysource.FieldSyncEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field sync_enabled", values[i])
			} else if value.Valid {
				_m.SyncEnabled = value.Bool
			}
		case proxysource.FieldSubTrafficUsed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sub_traffic_used", values[i])
			} else if value.Valid {
				_m.SubTrafficUsed = value.Int64
			}
		case proxysource.FieldSubTrafficTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sub_traffic_total", values[i])
			} else if value.Valid {
				_m.SubTrafficTotal = value.Int64
			}
		case proxysource.FieldSubExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sub_expires_at", values[i])
			} else if value.Valid {
				_m.SubExpiresAt = new(time.Time)
				*_m.SubExpiresAt = value.Time
			}
		case proxysource.FieldSubInfoUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sub_info_updated_at", values[i])
			} else if value.Valid {
				_m.SubInfoUpdatedAt = new(time.Time)
				*_m.SubInfoUpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxySource.
// This includes values selected through modifiers, order, etc.
func (_m *ProxySource) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProxySource.
// Note that you need to call ProxySource.Unwrap() before calling this method if this ProxySource
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxySource) Update() *ProxySourceUpdateOne {
	return NewProxySourceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxySource entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxySource) Unwrap() *ProxySource {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxySource is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxySource) String() string {
	var builder strings.Builder
	builder.WriteString("ProxySource(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.OwnerUserID; v != nil {
		builder.WriteString("owner_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("subscription_url=")
	builder.WriteString(_m.SubscriptionURL)
	builder.WriteString(", ")
	builder.WriteString("is_public=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPublic))
	builder.WriteString(", ")
	builder.WriteString("refresh_interval_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefreshIntervalMinutes))
	builder.WriteString(", ")
	if v := _m.LastSyncedAt; v != nil {
		builder.WriteString("last_synced_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_sync_status=")
	builder.WriteString(_m.LastSyncStatus)
	builder.WriteString(", ")
	if v := _m.LastSyncError; v != nil {
		builder.WriteString("last_sync_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("last_imported_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastImportedCount))
	builder.WriteString(", ")
	builder.WriteString("sync_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncEnabled))
	builder.WriteString(", ")
	builder.WriteString("sub_traffic_used=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubTrafficUsed))
	builder.WriteString(", ")
	builder.WriteString("sub_traffic_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubTrafficTotal))
	builder.WriteString(", ")
	if v := _m.SubExpiresAt; v != nil {
		builder.WriteString("sub_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SubInfoUpdatedAt; v != nil {
		builder.WriteString("sub_info_updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ProxySources is a parsable slice of ProxySource.
type ProxySources []*ProxySource
