// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/proxysource"
)

// ProxySourceUpdate is the builder for updating ProxySource entities.
type ProxySourceUpdate struct {
	config
	hooks    []Hook
	mutation *ProxySourceMutation
}

// Where appends a list predicates to the ProxySourceUpdate builder.
func (_u *ProxySourceUpdate) Where(ps ...predicate.ProxySource) *ProxySourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxySourceUpdate) SetUpdatedAt(v time.Time) *ProxySourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxySourceUpdate) SetDeletedAt(v time.Time) *ProxySourceUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxySourceUpdate) SetNillableDeletedAt(v *time.Time) *ProxySourceUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxySourceUpdate) ClearDeletedAt() *ProxySourceUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *ProxySourceUpdate) SetOwnerUserID(v int64) *ProxySourceUpdate {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *ProxySourceUpdate) SetNillableOwnerUserID(v *int64) *ProxySourceUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *ProxySourceUpdate) AddOwnerUserID(v int64) *ProxySourceUpdate {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (_u *ProxySourceUpdate) ClearOwnerUserID() *ProxySourceUpdate {
	_u.mutation.ClearOwnerUserID()
	return _u
}

// SetName sets the "name" field.
func (_u *ProxySourceUpdate) SetName(v string) *ProxySourceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxySourceUpdate) SetNillableName(v *string) *ProxySourceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSubscriptionURL sets the "subscription_url" field.
func (_u *ProxySourceUpdate) SetSubscriptionURL(v string) *ProxySourceUpdate {
	_u.mutation.SetSubscriptionURL(v)
	return _u
}

// SetNillableSubscriptionURL sets the "subscription_url" field if the given value is not nil.
func (_u *ProxySourceUpdate) SetNillableSubscriptionURL(v *string) *ProxySourceUpdate {
	if v != nil {
		_u.SetSubscriptionURL(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *ProxySourceUpdate) SetIsPublic(v bool) *ProxySourceUpdate {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *ProxySourceUpdate) SetNillableIsPublic(v *bool) *ProxySourceUpdate {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetRefreshIntervalMinutes sets the "refresh_interval_minutes" field.
func (_u *ProxySourceUpdate) SetRefreshIntervalMinutes(v int) *ProxySourceUpdate {
	_u.mutation.ResetRefreshIntervalMinutes()
	_u.mutation.SetRefreshIntervalMinutes(v)
	return _u
}

// SetNillableRefreshIntervalMinutes sets the "refresh_interval_minutes" field if the given value is not nil.
func (_u *ProxySourceUpdate) SetNillableRefreshIntervalMinutes(v *int) *ProxySourceUpdate {
	if v != nil {
		_u.SetRefreshIntervalMinutes(*v)
	}
	return _u
}

// AddRefreshIntervalMinutes adds value to the "refresh_interval_minutes" field.
func (_u *ProxySourceUpdate) AddRefreshIntervalMinutes(v int) *ProxySourceUpdate {
	_u.mutation.AddRefreshIntervalMinutes(v)
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *ProxySourceUpdate) SetLastSyncedAt(v time.Time) *ProxySourceUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *ProxySourceUpdate) SetNillableLastSyncedAt(v *time.Time) *ProxySourceUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *ProxySourceUpdate) ClearLastSyncedAt() *ProxySourceUpdate {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (_u *ProxySourceUpdate) SetLastSyncStatus(v string) *ProxySourceUpdate {
	_u.mutation.SetLastSyncStatus(v)
	return _u
}

// SetNillableLastSyncStatus sets the "last_sync_status" field if the given value is not nil.
func (_u *ProxySourceUpdate) SetNillableLastSyncStatus(v *string) *ProxySourceUpdate {
	if v != nil {
		_u.SetLastSyncStatus(*v)
	}
	return _u
}

// SetLastSyncError sets the "last_sync_error" field.
func (_u *ProxySourceUpdate) SetLastSyncError(v string) *ProxySourceUpdate {
	_u.mutation.SetLastSyncError(v)
	return _u
}

// SetNillableLastSyncError sets the "last_sync_error" field if the given value is not nil.
func (_u *ProxySourceUpdate) SetNillableLastSyncError(v *string) *ProxySourceUpdate {
	if v != nil {
		_u.SetLastSyncError(*v)
	}
	return _u
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (_u *ProxySourceUpdate) ClearLastSyncError() *ProxySourceUpdate {
	_u.mutation.ClearLastSyncError()
	return _u
}

// SetLastImportedCount sets the "last_imported_count" field.
func (_u *ProxySourceUpdate) SetLastImportedCount(v int) *ProxySourceUpdate {
	_u.mutation.ResetLastImportedCount()
	_u.mutation.SetLastImportedCount(v)
	return _u
}

// SetNillableLastImportedCount sets the "last_imported_count" field if the given value is not nil.
func (_u *ProxySourceUpdate) SetNillableLastImportedCount(v *int) *ProxySourceUpdate {
	if v != nil {
		_u.SetLastImportedCount(*v)
	}
	return _u
}

// AddLastImportedCount adds value to the "last_imported_count" field.
func (_u *ProxySourceUpdate) AddLastImportedCount(v int) *ProxySourceUpdate {
	_u.mutation.AddLastImportedCount(v)
	return _u
}

// SetSyncEnabled sets the "sync_enabled" field.
func (_u *ProxySourceUpdate) SetSyncEnabled(v bool) *ProxySourceUpdate {
	_u.mutation.SetSyncEnabled(v)
	return _u
}

// SetNillableSyncEnabled sets the "sync_enabled" field if the given value is not nil.
func (_u *ProxySourceUpdate) SetNillableSyncEnabled(v *bool) *ProxySourceUpdate {
	if v != nil {
		_u.SetSyncEnabled(*v)
	}
	return _u
}

// SetSubTrafficUsed sets the "sub_traffic_used" field.
func (_u *ProxySourceUpdate) SetSubTrafficUsed(v int64) *ProxySourceUpdate {
	_u.mutation.ResetSubTrafficUsed()
	_u.mutation.SetSubTrafficUsed(v)
	return _u
}

// SetNillableSubTrafficUsed sets the "sub_traffic_used" field if the given value is not nil.
func (_u *ProxySourceUpdate) SetNillableSubTrafficUsed(v *int64) *ProxySourceUpdate {
	if v != nil {
		_u.SetSubTrafficUsed(*v)
	}
	return _u
}

// AddSubTrafficUsed adds value to the "sub_traffic_used" field.
func (_u *ProxySourceUpdate) AddSubTrafficUsed(v int64) *ProxySourceUpdate {
	_u.mutation.AddSubTrafficUsed(v)
	return _u
}

// SetSubTrafficTotal sets the "sub_traffic_total" field.
func (_u *ProxySourceUpdate) SetSubTrafficTotal(v int64) *ProxySourceUpdate {
	_u.mutation.ResetSubTrafficTotal()
	_u.mutation.SetSubTrafficTotal(v)
	return _u
}

// SetNillableSubTrafficTotal sets the "sub_traffic_total" field if the given value is not nil.
func (_u *ProxySourceUpdate) SetNillableSubTrafficTotal(v *int64) *ProxySourceUpdate {
	if v != nil {
		_u.SetSubTrafficTotal(*v)
	}
	return _u
}

// AddSubTrafficTotal adds value to the "sub_traffic_total" field.
func (_u *ProxySourceUpdate) AddSubTrafficTotal(v int64) *ProxySourceUpdate {
	_u.mutation.AddSubTrafficTotal(v)
	return _u
}

// SetSubExpiresAt sets the "sub_expires_at" field.
func (_u *ProxySourceUpdate) SetSubExpiresAt(v time.Time) *ProxySourceUpdate {
	_u.mutation.SetSubExpiresAt(v)
	return _u
}

// SetNillableSubExpiresAt sets the "sub_expires_at" field if the given value is not nil.
func (_u *ProxySourceUpdate) SetNillableSubExpiresAt(v *time.Time) *ProxySourceUpdate {
	if v != nil {
		_u.SetSubExpiresAt(*v)
	}
	return _u
}

// ClearSubExpiresAt clears the value of the "sub_expires_at" field.
func (_u *ProxySourceUpdate) ClearSubExpiresAt() *ProxySourceUpdate {
	_u.mutation.ClearSubExpiresAt()
	return _u
}

// SetSubInfoUpdatedAt sets the "sub_info_updated_at" field.
func (_u *ProxySourceUpdate) SetSubInfoUpdatedAt(v time.Time) *ProxySourceUpdate {
	_u.mutation.SetSubInfoUpdatedAt(v)
	return _u
}

// SetNillableSubInfoUpdatedAt sets the "sub_info_updated_at" field if the given value is not nil.
func (_u *ProxySourceUpdate) SetNillableSubInfoUpdatedAt(v *time.Time) *ProxySourceUpdate {
	if v != nil {
		_u.SetSubInfoUpdatedAt(*v)
	}
	return _u
}

// ClearSubInfoUpdatedAt clears the value of the "sub_info_updated_at" field.
func (_u *ProxySourceUpdate) ClearSubInfoUpdatedAt() *ProxySourceUpdate {
	_u.mutation.ClearSubInfoUpdatedAt()
	return _u
}

// Mutation returns the ProxySourceMutation object of the builder.
func (_u *ProxySourceUpdate) Mutation() *ProxySourceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxySourceUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxySourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxySourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxySourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxySourceUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if proxysource.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxysource.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxysource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxySourceUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxysource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxySource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubscriptionURL(); ok {
		if err := proxysource.SubscriptionURLValidator(v); err != nil {
			return &ValidationError{Name: "subscription_url", err: fmt.Errorf(`ent: validator failed for field "ProxySource.subscription_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastSyncStatus(); ok {
		if err := proxysource.LastSyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_sync_status", err: fmt.Errorf(`ent: validator failed for field "ProxySource.last_sync_status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxySourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxysource.Table, proxysource.Columns, sqlgraph.NewFieldSpec(proxysource.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxysource.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxysource.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(proxysource.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(proxysource.FieldOwnerUserID, field.TypeInt64, value)
	}
	if _u.mutation.OwnerUserIDCleared() {
		_spec.ClearField(proxysource.FieldOwnerUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxysource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionURL(); ok {
		_spec.SetField(proxysource.FieldSubscriptionURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(proxysource.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RefreshIntervalMinutes(); ok {
		_spec.SetField(proxysource.FieldRefreshIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefreshIntervalMinutes(); ok {
		_spec.AddField(proxysource.FieldRefreshIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(proxysource.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(proxysource.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSyncStatus(); ok {
		_spec.SetField(proxysource.FieldLastSyncStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncError(); ok {
		_spec.SetField(proxysource.FieldLastSyncError, field.TypeString, value)
	}
	if _u.mutation.LastSyncErrorCleared() {
		_spec.ClearField(proxysource.FieldLastSyncError, field.TypeString)
	}
	if value, ok := _u.mutation.LastImportedCount(); ok {
		_spec.SetField(proxysource.FieldLastImportedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastImportedCount(); ok {
		_spec.AddField(proxysource.FieldLastImportedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SyncEnabled(); ok {
		_spec.SetField(proxysource.FieldSyncEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SubTrafficUsed(); ok {
		_spec.SetField(proxysource.FieldSubTrafficUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubTrafficUsed(); ok {
		_spec.AddField(proxysource.FieldSubTrafficUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubTrafficTotal(); ok {
		_spec.SetField(proxysource.FieldSubTrafficTotal, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubTrafficTotal(); ok {
		_spec.AddField(proxysource.FieldSubTrafficTotal, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubExpiresAt(); ok {
		_spec.SetField(proxysource.FieldSubExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.SubExpiresAtCleared() {
		_spec.ClearField(proxysource.FieldSubExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SubInfoUpdatedAt(); ok {
		_spec.SetField(proxysource.FieldSubInfoUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SubInfoUpdatedAtCleared() {
		_spec.ClearField(proxysource.FieldSubInfoUpdatedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxysource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxySourceUpdateOne is the builder for updating a single ProxySource entity.
type ProxySourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxySourceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxySourceUpdateOne) SetUpdatedAt(v time.Time) *ProxySourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxySourceUpdateOne) SetDeletedAt(v time.Time) *ProxySourceUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxySourceUpdateOne) SetNillableDeletedAt(v *time.Time) *ProxySourceUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxySourceUpdateOne) ClearDeletedAt() *ProxySourceUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *ProxySourceUpdateOne) SetOwnerUserID(v int64) *ProxySourceUpdateOne {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *ProxySourceUpdateOne) SetNillableOwnerUserID(v *int64) *ProxySourceUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *ProxySourceUpdateOne) AddOwnerUserID(v int64) *ProxySourceUpdateOne {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (_u *ProxySourceUpdateOne) ClearOwnerUserID() *ProxySourceUpdateOne {
	_u.mutation.ClearOwnerUserID()
	return _u
}

// SetName sets the "name" field.
func (_u *ProxySourceUpdateOne) SetName(v string) *ProxySourceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxySourceUpdateOne) SetNillableName(v *string) *ProxySourceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSubscriptionURL sets the "subscription_url" field.
func (_u *ProxySourceUpdateOne) SetSubscriptionURL(v string) *ProxySourceUpdateOne {
	_u.mutation.SetSubscriptionURL(v)
	return _u
}

// SetNillableSubscriptionURL sets the "subscription_url" field if the given value is not nil.
func (_u *ProxySourceUpdateOne) SetNillableSubscriptionURL(v *string) *ProxySourceUpdateOne {
	if v != nil {
		_u.SetSubscriptionURL(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *ProxySourceUpdateOne) SetIsPublic(v bool) *ProxySourceUpdateOne {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *ProxySourceUpdateOne) SetNillableIsPublic(v *bool) *ProxySourceUpdateOne {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetRefreshIntervalMinutes sets the "refresh_interval_minutes" field.
func (_u *ProxySourceUpdateOne) SetRefreshIntervalMinutes(v int) *ProxySourceUpdateOne {
	_u.mutation.ResetRefreshIntervalMinutes()
	_u.mutation.SetRefreshIntervalMinutes(v)
	return _u
}

// SetNillableRefreshIntervalMinutes sets the "refresh_interval_minutes" field if the given value is not nil.
func (_u *ProxySourceUpdateOne) SetNillableRefreshIntervalMinutes(v *int) *ProxySourceUpdateOne {
	if v != nil {
		_u.SetRefreshIntervalMinutes(*v)
	}
	return _u
}

// AddRefreshIntervalMinutes adds value to the "refresh_interval_minutes" field.
func (_u *ProxySourceUpdateOne) AddRefreshIntervalMinutes(v int) *ProxySourceUpdateOne {
	_u.mutation.AddRefreshIntervalMinutes(v)
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *ProxySourceUpdateOne) SetLastSyncedAt(v time.Time) *ProxySourceUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *ProxySourceUpdateOne) SetNillableLastSyncedAt(v *time.Time) *ProxySourceUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *ProxySourceUpdateOne) ClearLastSyncedAt() *ProxySourceUpdateOne {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (_u *ProxySourceUpdateOne) SetLastSyncStatus(v string) *ProxySourceUpdateOne {
	_u.mutation.SetLastSyncStatus(v)
	return _u
}

// SetNillableLastSyncStatus sets the "last_sync_status" field if the given value is not nil.
func (_u *ProxySourceUpdateOne) SetNillableLastSyncStatus(v *string) *ProxySourceUpdateOne {
	if v != nil {
		_u.SetLastSyncStatus(*v)
	}
	return _u
}

// SetLastSyncError sets the "last_sync_error" field.
func (_u *ProxySourceUpdateOne) SetLastSyncError(v string) *ProxySourceUpdateOne {
	_u.mutation.SetLastSyncError(v)
	return _u
}

// SetNillableLastSyncError sets the "last_sync_error" field if the given value is not nil.
func (_u *ProxySourceUpdateOne) SetNillableLastSyncError(v *string) *ProxySourceUpdateOne {
	if v != nil {
		_u.SetLastSyncError(*v)
	}
	return _u
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (_u *ProxySourceUpdateOne) ClearLastSyncError() *ProxySourceUpdateOne {
	_u.mutation.ClearLastSyncError()
	return _u
}

// SetLastImportedCount sets the "last_imported_count" field.
func (_u *ProxySourceUpdateOne) SetLastImportedCount(v int) *ProxySourceUpdateOne {
	_u.mutation.ResetLastImportedCount()
	_u.mutation.SetLastImportedCount(v)
	return _u
}

// SetNillableLastImportedCount sets the "last_imported_count" field if the given value is not nil.
func (_u *ProxySourceUpdateOne) SetNillableLastImportedCount(v *int) *ProxySourceUpdateOne {
	if v != nil {
		_u.SetLastImportedCount(*v)
	}
	return _u
}

// AddLastImportedCount adds value to the "last_imported_count" field.
func (_u *ProxySourceUpdateOne) AddLastImportedCount(v int) *ProxySourceUpdateOne {
	_u.mutation.AddLastImportedCount(v)
	return _u
}

// SetSyncEnabled sets the "sync_enabled" field.
func (_u *ProxySourceUpdateOne) SetSyncEnabled(v bool) *ProxySourceUpdateOne {
	_u.mutation.SetSyncEnabled(v)
	return _u
}

// SetNillableSyncEnabled sets the "sync_enabled" field if the given value is not nil.
func (_u *ProxySourceUpdateOne) SetNillableSyncEnabled(v *bool) *ProxySourceUpdateOne {
	if v != nil {
		_u.SetSyncEnabled(*v)
	}
	return _u
}

// SetSubTrafficUsed sets the "sub_traffic_used" field.
func (_u *ProxySourceUpdateOne) SetSubTrafficUsed(v int64) *ProxySourceUpdateOne {
	_u.mutation.ResetSubTrafficUsed()
	_u.mutation.SetSubTrafficUsed(v)
	return _u
}

// SetNillableSubTrafficUsed sets the "sub_traffic_used" field if the given value is not nil.
func (_u *ProxySourceUpdateOne) SetNillableSubTrafficUsed(v *int64) *ProxySourceUpdateOne {
	if v != nil {
		_u.SetSubTrafficUsed(*v)
	}
	return _u
}

// AddSubTrafficUsed adds value to the "sub_traffic_used" field.
func (_u *ProxySourceUpdateOne) AddSubTrafficUsed(v int64) *ProxySourceUpdateOne {
	_u.mutation.AddSubTrafficUsed(v)
	return _u
}

// SetSubTrafficTotal sets the "sub_traffic_total" field.
func (_u *ProxySourceUpdateOne) SetSubTrafficTotal(v int64) *ProxySourceUpdateOne {
	_u.mutation.ResetSubTrafficTotal()
	_u.mutation.SetSubTrafficTotal(v)
	return _u
}

// SetNillableSubTrafficTotal sets the "sub_traffic_total" field if the given value is not nil.
func (_u *ProxySourceUpdateOne) SetNillableSubTrafficTotal(v *int64) *ProxySourceUpdateOne {
	if v != nil {
		_u.SetSubTrafficTotal(*v)
	}
	return _u
}

// AddSubTrafficTotal adds value to the "sub_traffic_total" field.
func (_u *ProxySourceUpdateOne) AddSubTrafficTotal(v int64) *ProxySourceUpdateOne {
	_u.mutation.AddSubTrafficTotal(v)
	return _u
}

// SetSubExpiresAt sets the "sub_expires_at" field.
func (_u *ProxySourceUpdateOne) SetSubExpiresAt(v time.Time) *ProxySourceUpdateOne {
	_u.mutation.SetSubExpiresAt(v)
	return _u
}

// SetNillableSubExpiresAt sets the "sub_expires_at" field if the given value is not nil.
func (_u *ProxySourceUpdateOne) SetNillableSubExpiresAt(v *time.Time) *ProxySourceUpdateOne {
	if v != nil {
		_u.SetSubExpiresAt(*v)
	}
	return _u
}

// ClearSubExpiresAt clears the value of the "sub_expires_at" field.
func (_u *ProxySourceUpdateOne) ClearSubExpiresAt() *ProxySourceUpdateOne {
	_u.mutation.ClearSubExpiresAt()
	return _u
}

// SetSubInfoUpdatedAt sets the "sub_info_updated_at" field.
func (_u *ProxySourceUpdateOne) SetSubInfoUpdatedAt(v time.Time) *ProxySourceUpdateOne {
	_u.mutation.SetSubInfoUpdatedAt(v)
	return _u
}

// SetNillableSubInfoUpdatedAt sets the "sub_info_updated_at" field if the given value is not nil.
func (_u *ProxySourceUpdateOne) SetNillableSubInfoUpdatedAt(v *time.Time) *ProxySourceUpdateOne {
	if v != nil {
		_u.SetSubInfoUpdatedAt(*v)
	}
	return _u
}

// ClearSubInfoUpdatedAt clears the value of the "sub_info_updated_at" field.
func (_u *ProxySourceUpdateOne) ClearSubInfoUpdatedAt() *ProxySourceUpdateOne {
	_u.mutation.ClearSubInfoUpdatedAt()
	return _u
}

// Mutation returns the ProxySourceMutation object of the builder.
func (_u *ProxySourceUpdateOne) Mutation() *ProxySourceMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProxySourceUpdate builder.
func (_u *ProxySourceUpdateOne) Where(ps ...predicate.ProxySource) *ProxySourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxySourceUpdateOne) Select(field string, fields ...string) *ProxySourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxySource entity.
func (_u *ProxySourceUpdateOne) Save(ctx context.Context) (*ProxySource, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxySourceUpdateOne) SaveX(ctx context.Context) *ProxySource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxySourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxySourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxySourceUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if proxysource.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxysource.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxysource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxySourceUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxysource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxySource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubscriptionURL(); ok {
		if err := proxysource.SubscriptionURLValidator(v); err != nil {
			return &ValidationError{Name: "subscription_url", err: fmt.Errorf(`ent: validator failed for field "ProxySource.subscription_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastSyncStatus(); ok {
		if err := proxysource.LastSyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_sync_status", err: fmt.Errorf(`ent: validator failed for field "ProxySource.last_sync_status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxySourceUpdateOne) sqlSave(ctx context.Context) (_node *ProxySource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxysource.Table, proxysource.Columns, sqlgraph.NewFieldSpec(proxysource.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxySource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxysource.FieldID)
		for _, f := range fields {
			if !proxysource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxysource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxysource.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxysource.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(proxysource.FieldOwnerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(proxysource.FieldOwnerUserID, field.TypeInt64, value)
	}
	if _u.mutation.OwnerUserIDCleared() {
		_spec.ClearField(proxysource.FieldOwnerUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxysource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionURL(); ok {
		_spec.SetField(proxysource.FieldSubscriptionURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(proxysource.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RefreshIntervalMinutes(); ok {
		_spec.SetField(proxysource.FieldRefreshIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefreshIntervalMinutes(); ok {
		_spec.AddField(proxysource.FieldRefreshIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(proxysource.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(proxysource.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSyncStatus(); ok {
		_spec.SetField(proxysource.FieldLastSyncStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncError(); ok {
		_spec.SetField(proxysource.FieldLastSyncError, field.TypeString, value)
	}
	if _u.mutation.LastSyncErrorCleared() {
		_spec.ClearField(proxysource.FieldLastSyncError, field.TypeString)
	}
	if value, ok := _u.mutation.LastImportedCount(); ok {
		_spec.SetField(proxysource.FieldLastImportedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastImportedCount(); ok {
		_spec.AddField(proxysource.FieldLastImportedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SyncEnabled(); ok {
		_spec.SetField(proxysource.FieldSyncEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SubTrafficUsed(); ok {
		_spec.SetField(proxysource.FieldSubTrafficUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubTrafficUsed(); ok {
		_spec.AddField(proxysource.FieldSubTrafficUsed, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubTrafficTotal(); ok {
		_spec.SetField(proxysource.FieldSubTrafficTotal, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubTrafficTotal(); ok {
		_spec.AddField(proxysource.FieldSubTrafficTotal, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubExpiresAt(); ok {
		_spec.SetField(proxysource.FieldSubExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.SubExpiresAtCleared() {
		_spec.ClearField(proxysource.FieldSubExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SubInfoUpdatedAt(); ok {
		_spec.SetField(proxysource.FieldSubInfoUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SubInfoUpdatedAtCleared() {
		_spec.ClearField(proxysource.FieldSubInfoUpdatedAt, field.TypeTime)
	}
	_node = &ProxySource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxysource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
