// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/redeemcodeusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RedeemCodeUsageUpdate is the builder for updating RedeemCodeUsage entities.
type RedeemCodeUsageUpdate struct {
	config
	hooks    []Hook
	mutation *RedeemCodeUsageMutation
}

// Where appends a list predicates to the RedeemCodeUsageUpdate builder.
func (_u *RedeemCodeUsageUpdate) Where(ps ...predicate.RedeemCodeUsage) *RedeemCodeUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *RedeemCodeUsageUpdate) SetRedeemCodeID(v int64) *RedeemCodeUsageUpdate {
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *RedeemCodeUsageUpdate) SetNillableRedeemCodeID(v *int64) *RedeemCodeUsageUpdate {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RedeemCodeUsageUpdate) SetUserID(v int64) *RedeemCodeUsageUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RedeemCodeUsageUpdate) SetNillableUserID(v *int64) *RedeemCodeUsageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *RedeemCodeUsageUpdate) SetUsedAt(v time.Time) *RedeemCodeUsageUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *RedeemCodeUsageUpdate) SetNillableUsedAt(v *time.Time) *RedeemCodeUsageUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// SetRedeemCode sets the "redeem_code" edge to the RedeemCode entity.
func (_u *RedeemCodeUsageUpdate) SetRedeemCode(v *RedeemCode) *RedeemCodeUsageUpdate {
	return _u.SetRedeemCodeID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *RedeemCodeUsageUpdate) SetUser(v *User) *RedeemCodeUsageUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the RedeemCodeUsageMutation object of the builder.
func (_u *RedeemCodeUsageUpdate) Mutation() *RedeemCodeUsageMutation {
	return _u.mutation
}

// ClearRedeemCode clears the "redeem_code" edge to the RedeemCode entity.
func (_u *RedeemCodeUsageUpdate) ClearRedeemCode() *RedeemCodeUsageUpdate {
	_u.mutation.ClearRedeemCode()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RedeemCodeUsageUpdate) ClearUser() *RedeemCodeUsageUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RedeemCodeUsageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemCodeUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RedeemCodeUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemCodeUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RedeemCodeUsageUpdate) check() error {
	if _u.mutation.RedeemCodeCleared() && len(_u.mutation.RedeemCodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RedeemCodeUsage.redeem_code"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RedeemCodeUsage.user"`)
	}
	return nil
}

func (_u *RedeemCodeUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(redeemcodeusage.Table, redeemcodeusage.Columns, sqlgraph.NewFieldSpec(redeemcodeusage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(redeemcodeusage.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.RedeemCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeusage.RedeemCodeTable,
			Columns: []string{redeemcodeusage.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeusage.RedeemCodeTable,
			Columns: []string{redeemcodeusage.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeusage.UserTable,
			Columns: []string{redeemcodeusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeusage.UserTable,
			Columns: []string{redeemcodeusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemcodeusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RedeemCodeUsageUpdateOne is the builder for updating a single RedeemCodeUsage entity.
type RedeemCodeUsageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RedeemCodeUsageMutation
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *RedeemCodeUsageUpdateOne) SetRedeemCodeID(v int64) *RedeemCodeUsageUpdateOne {
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *RedeemCodeUsageUpdateOne) SetNillableRedeemCodeID(v *int64) *RedeemCodeUsageUpdateOne {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RedeemCodeUsageUpdateOne) SetUserID(v int64) *RedeemCodeUsageUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RedeemCodeUsageUpdateOne) SetNillableUserID(v *int64) *RedeemCodeUsageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *RedeemCodeUsageUpdateOne) SetUsedAt(v time.Time) *RedeemCodeUsageUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *RedeemCodeUsageUpdateOne) SetNillableUsedAt(v *time.Time) *RedeemCodeUsageUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// SetRedeemCode sets the "redeem_code" edge to the RedeemCode entity.
func (_u *RedeemCodeUsageUpdateOne) SetRedeemCode(v *RedeemCode) *RedeemCodeUsageUpdateOne {
	return _u.SetRedeemCodeID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *RedeemCodeUsageUpdateOne) SetUser(v *User) *RedeemCodeUsageUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the RedeemCodeUsageMutation object of the builder.
func (_u *RedeemCodeUsageUpdateOne) Mutation() *RedeemCodeUsageMutation {
	return _u.mutation
}

// ClearRedeemCode clears the "redeem_code" edge to the RedeemCode entity.
func (_u *RedeemCodeUsageUpdateOne) ClearRedeemCode() *RedeemCodeUsageUpdateOne {
	_u.mutation.ClearRedeemCode()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RedeemCodeUsageUpdateOne) ClearUser() *RedeemCodeUsageUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the RedeemCodeUsageUpdate builder.
func (_u *RedeemCodeUsageUpdateOne) Where(ps ...predicate.RedeemCodeUsage) *RedeemCodeUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RedeemCodeUsageUpdateOne) Select(field string, fields ...string) *RedeemCodeUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RedeemCodeUsage entity.
func (_u *RedeemCodeUsageUpdateOne) Save(ctx context.Context) (*RedeemCodeUsage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemCodeUsageUpdateOne) SaveX(ctx context.Context) *RedeemCodeUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RedeemCodeUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemCodeUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RedeemCodeUsageUpdateOne) check() error {
	if _u.mutation.RedeemCodeCleared() && len(_u.mutation.RedeemCodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RedeemCodeUsage.redeem_code"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RedeemCodeUsage.user"`)
	}
	return nil
}

func (_u *RedeemCodeUsageUpdateOne) sqlSave(ctx context.Context) (_node *RedeemCodeUsage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(redeemcodeusage.Table, redeemcodeusage.Columns, sqlgraph.NewFieldSpec(redeemcodeusage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RedeemCodeUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, redeemcodeusage.FieldID)
		for _, f := range fields {
			if !redeemcodeusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != redeemcodeusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(redeemcodeusage.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.RedeemCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeusage.RedeemCodeTable,
			Columns: []string{redeemcodeusage.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeusage.RedeemCodeTable,
			Columns: []string{redeemcodeusage.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeusage.UserTable,
			Columns: []string{redeemcodeusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeusage.UserTable,
			Columns: []string{redeemcodeusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RedeemCodeUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemcodeusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
