// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcodeusage"
)

// RedeemCodeUsageDelete is the builder for deleting a RedeemCodeUsage entity.
type RedeemCodeUsageDelete struct {
	config
	hooks    []Hook
	mutation *RedeemCodeUsageMutation
}

// Where appends a list predicates to the RedeemCodeUsageDelete builder.
func (_d *RedeemCodeUsageDelete) Where(ps ...predicate.RedeemCodeUsage) *RedeemCodeUsageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RedeemCodeUsageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RedeemCodeUsageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RedeemCodeUsageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(redeemcodeusage.Table, sqlgraph.NewFieldSpec(redeemcodeusage.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RedeemCodeUsageDeleteOne is the builder for deleting a single RedeemCodeUsage entity.
type RedeemCodeUsageDeleteOne struct {
	_d *RedeemCodeUsageDelete
}

// Where appends a list predicates to the RedeemCodeUsageDelete builder.
func (_d *RedeemCodeUsageDeleteOne) Where(ps ...predicate.RedeemCodeUsage) *RedeemCodeUsageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RedeemCodeUsageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{redeemcodeusage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RedeemCodeUsageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
