// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/redeemcodeusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RedeemCodeUsage is the model entity for the RedeemCodeUsage schema.
type RedeemCodeUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RedeemCodeID holds the value of the "redeem_code_id" field.
	RedeemCodeID int64 `json:"redeem_code_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// UsedAt holds the value of the "used_at" field.
	UsedAt time.Time `json:"used_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RedeemCodeUsageQuery when eager-loading is set.
	Edges        RedeemCodeUsageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RedeemCodeUsageEdges holds the relations/edges for other nodes in the graph.
type RedeemCodeUsageEdges struct {
	// RedeemCode holds the value of the redeem_code edge.
	RedeemCode *RedeemCode `json:"redeem_code,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RedeemCodeOrErr returns the RedeemCode value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RedeemCodeUsageEdges) RedeemCodeOrErr() (*RedeemCode, error) {
	if e.RedeemCode != nil {
		return e.RedeemCode, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: redeemcode.Label}
	}
	return nil, &NotLoadedError{edge: "redeem_code"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RedeemCodeUsageEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RedeemCodeUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case redeemcodeusage.FieldID, redeemcodeusage.FieldRedeemCodeID, redeemcodeusage.FieldUserID:
			values[i] = new(sql.NullInt64)
		case redeemcodeusage.FieldUsedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RedeemCodeUsage fields.
func (_m *RedeemCodeUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case redeemcodeusage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case redeemcodeusage.FieldRedeemCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field redeem_code_id", values[i])
			} else if value.Valid {
				_m.RedeemCodeID = value.Int64
			}
		case redeemcodeusage.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case redeemcodeusage.FieldUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field used_at", values[i])
			} else if value.Valid {
				_m.UsedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RedeemCodeUsage.
// This includes values selected through modifiers, order, etc.
func (_m *RedeemCodeUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRedeemCode queries the "redeem_code" edge of the RedeemCodeUsage entity.
func (_m *RedeemCodeUsage) QueryRedeemCode() *RedeemCodeQuery {
	return NewRedeemCodeUsageClient(_m.config).QueryRedeemCode(_m)
}

// QueryUser queries the "user" edge of the RedeemCodeUsage entity.
func (_m *RedeemCodeUsage) QueryUser() *UserQuery {
	return NewRedeemCodeUsageClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this RedeemCodeUsage.
// Note that you need to call RedeemCodeUsage.Unwrap() before calling this method if this RedeemCodeUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RedeemCodeUsage) Update() *RedeemCodeUsageUpdateOne {
	return NewRedeemCodeUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RedeemCodeUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RedeemCodeUsage) Unwrap() *RedeemCodeUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RedeemCodeUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RedeemCodeUsage) String() string {
	var builder strings.Builder
	builder.WriteString("RedeemCodeUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("redeem_code_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RedeemCodeID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("used_at=")
	builder.WriteString(_m.UsedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RedeemCodeUsages is a parsable slice of RedeemCodeUsage.
type RedeemCodeUsages []*RedeemCodeUsage
