// Code generated by ent, DO NOT EDIT.

package redeemcodeusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the redeemcodeusage type in the database.
	Label = "redeem_code_usage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRedeemCodeID holds the string denoting the redeem_code_id field in the database.
	FieldRedeemCodeID = "redeem_code_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUsedAt holds the string denoting the used_at field in the database.
	FieldUsedAt = "used_at"
	// EdgeRedeemCode holds the string denoting the redeem_code edge name in mutations.
	EdgeRedeemCode = "redeem_code"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the redeemcodeusage in the database.
	Table = "redeem_code_usages"
	// RedeemCodeTable is the table that holds the redeem_code relation/edge.
	RedeemCodeTable = "redeem_code_usages"
	// RedeemCodeInverseTable is the table name for the RedeemCode entity.
	// It exists in this package in order to avoid circular dependency with the "redeemcode" package.
	RedeemCodeInverseTable = "redeem_codes"
	// RedeemCodeColumn is the table column denoting the redeem_code relation/edge.
	RedeemCodeColumn = "redeem_code_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "redeem_code_usages"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for redeemcodeusage fields.
var Columns = []string{
	FieldID,
	FieldRedeemCodeID,
	FieldUserID,
	FieldUsedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUsedAt holds the default value on creation for the "used_at" field.
	DefaultUsedAt func() time.Time
)

// OrderOption defines the ordering options for the RedeemCodeUsage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRedeemCodeID orders the results by the redeem_code_id field.
func ByRedeemCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemCodeID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUsedAt orders the results by the used_at field.
func ByUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedAt, opts...).ToFunc()
}

// ByRedeemCodeField orders the results by redeem_code field.
func ByRedeemCodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRedeemCodeStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newRedeemCodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RedeemCodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RedeemCodeTable, RedeemCodeColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
