// Code generated by ent, DO NOT EDIT.

package redeemcodeusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldLTE(FieldID, id))
}

// RedeemCodeID applies equality check predicate on the "redeem_code_id" field. It's identical to RedeemCodeIDEQ.
func RedeemCodeID(v int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldEQ(FieldRedeemCodeID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldEQ(FieldUserID, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldEQ(FieldUsedAt, v))
}

// RedeemCodeIDEQ applies the EQ predicate on the "redeem_code_id" field.
func RedeemCodeIDEQ(v int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDNEQ applies the NEQ predicate on the "redeem_code_id" field.
func RedeemCodeIDNEQ(v int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldNEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDIn applies the In predicate on the "redeem_code_id" field.
func RedeemCodeIDIn(vs ...int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDNotIn applies the NotIn predicate on the "redeem_code_id" field.
func RedeemCodeIDNotIn(vs ...int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldNotIn(FieldRedeemCodeID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldNotIn(FieldUserID, vs...))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.FieldLTE(FieldUsedAt, v))
}

// HasRedeemCode applies the HasEdge predicate on the "redeem_code" edge.
func HasRedeemCode() predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RedeemCodeTable, RedeemCodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRedeemCodeWith applies the HasEdge predicate on the "redeem_code" edge with a given conditions (other predicates).
func HasRedeemCodeWith(preds ...predicate.RedeemCode) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(func(s *sql.Selector) {
		step := newRedeemCodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RedeemCodeUsage) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RedeemCodeUsage) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RedeemCodeUsage) predicate.RedeemCodeUsage {
	return predicate.RedeemCodeUsage(sql.NotPredicates(p))
}
