// Code generated by ent, DO NOT EDIT.

package proxysource

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the proxysource type in the database.
	Label = "proxy_source"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldOwnerUserID holds the string denoting the owner_user_id field in the database.
	FieldOwnerUserID = "owner_user_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSubscriptionURL holds the string denoting the subscription_url field in the database.
	FieldSubscriptionURL = "subscription_url"
	// FieldIsPublic holds the string denoting the is_public field in the database.
	FieldIsPublic = "is_public"
	// FieldRefreshIntervalMinutes holds the string denoting the refresh_interval_minutes field in the database.
	FieldRefreshIntervalMinutes = "refresh_interval_minutes"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// FieldLastSyncStatus holds the string denoting the last_sync_status field in the database.
	FieldLastSyncStatus = "last_sync_status"
	// FieldLastSyncError holds the string denoting the last_sync_error field in the database.
	FieldLastSyncError = "last_sync_error"
	// FieldLastImportedCount holds the string denoting the last_imported_count field in the database.
	FieldLastImportedCount = "last_imported_count"
	// FieldSyncEnabled holds the string denoting the sync_enabled field in the database.
	FieldSyncEnabled = "sync_enabled"
	// FieldSubTrafficUsed holds the string denoting the sub_traffic_used field in the database.
	FieldSubTrafficUsed = "sub_traffic_used"
	// FieldSubTrafficTotal holds the string denoting the sub_traffic_total field in the database.
	FieldSubTrafficTotal = "sub_traffic_total"
	// FieldSubExpiresAt holds the string denoting the sub_expires_at field in the database.
	FieldSubExpiresAt = "sub_expires_at"
	// FieldSubInfoUpdatedAt holds the string denoting the sub_info_updated_at field in the database.
	FieldSubInfoUpdatedAt = "sub_info_updated_at"
	// Table holds the table name of the proxysource in the database.
	Table = "proxy_sources"
)

// Columns holds all SQL columns for proxysource fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldOwnerUserID,
	FieldName,
	FieldSubscriptionURL,
	FieldIsPublic,
	FieldRefreshIntervalMinutes,
	FieldLastSyncedAt,
	FieldLastSyncStatus,
	FieldLastSyncError,
	FieldLastImportedCount,
	FieldSyncEnabled,
	FieldSubTrafficUsed,
	FieldSubTrafficTotal,
	FieldSubExpiresAt,
	FieldSubInfoUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SubscriptionURLValidator is a validator for the "subscription_url" field. It is called by the builders before save.
	SubscriptionURLValidator func(string) error
	// DefaultIsPublic holds the default value on creation for the "is_public" field.
	DefaultIsPublic bool
	// DefaultRefreshIntervalMinutes holds the default value on creation for the "refresh_interval_minutes" field.
	DefaultRefreshIntervalMinutes int
	// DefaultLastSyncStatus holds the default value on creation for the "last_sync_status" field.
	DefaultLastSyncStatus string
	// LastSyncStatusValidator is a validator for the "last_sync_status" field. It is called by the builders before save.
	LastSyncStatusValidator func(string) error
	// DefaultLastImportedCount holds the default value on creation for the "last_imported_count" field.
	DefaultLastImportedCount int
	// DefaultSyncEnabled holds the default value on creation for the "sync_enabled" field.
	DefaultSyncEnabled bool
	// DefaultSubTrafficUsed holds the default value on creation for the "sub_traffic_used" field.
	DefaultSubTrafficUsed int64
	// DefaultSubTrafficTotal holds the default value on creation for the "sub_traffic_total" field.
	DefaultSubTrafficTotal int64
)

// OrderOption defines the ordering options for the ProxySource queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByOwnerUserID orders the results by the owner_user_id field.
func ByOwnerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerUserID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySubscriptionURL orders the results by the subscription_url field.
func BySubscriptionURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionURL, opts...).ToFunc()
}

// ByIsPublic orders the results by the is_public field.
func ByIsPublic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPublic, opts...).ToFunc()
}

// ByRefreshIntervalMinutes orders the results by the refresh_interval_minutes field.
func ByRefreshIntervalMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshIntervalMinutes, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}

// ByLastSyncStatus orders the results by the last_sync_status field.
func ByLastSyncStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncStatus, opts...).ToFunc()
}

// ByLastSyncError orders the results by the last_sync_error field.
func ByLastSyncError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncError, opts...).ToFunc()
}

// ByLastImportedCount orders the results by the last_imported_count field.
func ByLastImportedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastImportedCount, opts...).ToFunc()
}

// BySyncEnabled orders the results by the sync_enabled field.
func BySyncEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncEnabled, opts...).ToFunc()
}

// BySubTrafficUsed orders the results by the sub_traffic_used field.
func BySubTrafficUsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubTrafficUsed, opts...).ToFunc()
}

// BySubTrafficTotal orders the results by the sub_traffic_total field.
func BySubTrafficTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubTrafficTotal, opts...).ToFunc()
}

// BySubExpiresAt orders the results by the sub_expires_at field.
func BySubExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubExpiresAt, opts...).ToFunc()
}

// BySubInfoUpdatedAt orders the results by the sub_info_updated_at field.
func BySubInfoUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubInfoUpdatedAt, opts...).ToFunc()
}
